### ISSUE TITLE
what is the python version and torch version

### ISSUE THREAD

**Issue by pengzhangzhi** [SHI-Labs/Compact-Transformers#1]
`Traceback (most recent call last):
  File "main.py", line 251, in <module>
    main()
  File "main.py", line 105, in main
    patch_size=args.patch_size)
  File "C:\Users\彭张智computational AI\Desktop\Compact-Transformers-main\src\cct.py", line 326, in cct_7
    *args, **kwargs)
  File "C:\Users\彭张智computational AI\Desktop\Compact-Transformers-main\src\cct.py", line 286, in _cct
    *args, **kwargs)
  File "C:\Users\彭张智computational AI\Desktop\Compact-Transformers-main\src\cct.py", line 267, in __init__
    *args, **kwargs)
  File "C:\Users\彭张智computational AI\Desktop\Compact-Transformers-main\src\cct.py", line 98, in __init__
    nn.init.trunc_normal_(self.positional_emb, std=0.2)
AttributeError: module 'torch.nn.init' has no attribute 'trunc_normal_'
`

**Comment by alihassanijr** [comment]
Please use torch==1.8.1
